name: Ejecutar S

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Especifica la versión de Node.js que necesitas
    - name: Instalar dependencias
      run: npm install
    - name: Ejecutar script
      run: node index.js # Reemplaza tu-script.js con el nombre de tu archivo
